services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: API_ID
        value: "17082218"
      - key: API_HASH
        value: "6015a38682c3f6265ac55a1e35b1240a"
      - key: SOURCE_CHANNEL_ID
        value: "-1002279229082"
      - key: DESTINATION_CHANNEL_ID
        value: "-1002264693466"
